eivomt/loner_app

app/views/events/index.html.erb, db/seeds.rb
the next simple lines can be used to filter  by category and iterate trhough them as the arrays by category on  the carrousel. will find out how to do the "happening now" next. =)
=> created arrays by categories to be used in the index carrousels

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_users_show.scss, app/controllers/users_controller.rb, app/javascript/plugins/init_autocomplete.js, app/models/event.rb, app/models/user.rb, app/views/users/show.html.erb, db/migrate/20200225123117_removeimg_url_from_event.rb, db/schema.rb, db/seeds.rb
created a list of friends in each users show profile that prints the name
=> list of friends made

app/controllers/event_users_controller.rb, app/views/events/index.html.erb, app/views/events/show.html.erb, db/migrate/20200224123550_add_categories_to_events.rb, db/migrate/20200225164414_add_joined_to_event_user.rb, db/schema.rb, db/seeds.rb
the carrousels now display our events by categories. design needs to be cleaned. happening now carrousel needs to be displayed.
=> using the different event arrays on carrousels

app/views/events/_carrousel.html.erb, app/views/events/index.html.erb
created links to show from carrousels in index and cleaned the index with a carrousel partial
=> links and partial for carrousel

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_new.scss, app/controllers/events_controller.rb, app/views/events/_edit.html.erb, app/views/events/_form.html.erb, app/views/events/new.html.erb, config/routes.rb
Quick new and edit page. Need more design next week.
=> new and edit

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_users_show.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/pages/_show.scss, app/views/events/_carrousel.html.erb, app/views/users/show.html.erb
Hello!
Added different things to the user profil.
=> user profil

app/controllers/events_controller.rb, app/views/events/show.html.erb
our join / cancel button updates people missing ang going now!! jippiiiii!!! =)
=> Logic for join

app/views/shared/_navbar.html.erb, config/routes.rb
we can now use the user profile from the navbar
=> link to profile from navbar

app/views/devise/registrations/new.html.erb, app/views/events/show.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
unfinished, update doesnt work. still at it =)
=> seeds, navbar if logged in, update and delete event

app/views/events/edit.html.erb, app/views/events/show.html.erb, config/routes.rb
update present but has no form =)
changed quite a lot of stuff around, sorry!!
navbar list menu only present  if logged in, otherwise navbar shows a link to login instead
=> update still not available, but has a link

app/models/user.rb, app/views/events/edit.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, db/seeds.rb
users have pictures. there is one user for each student and some of the teachers tas
=> Seeds user

app/controllers/events_controller.rb, app/models/user.rb, app/views/events/_carousel.html.erb, app/views/events/index.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb, db/seeds.rb
friends ive made carrousel. it does not take into account if the event was in the past
=> Add carrousel ppl attending event

app/javascript/plugins/init_mapbox.js, app/models/event.rb, app/views/events/_carrousel-medium.html.erb, app/views/events/_map.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb
our events have a modal, will make a link to googlemaps
=> map on event show with  a marker

app/controllers/events_controller.rb, app/models/event.rb, app/views/events/show.html.erb
map markers are hearts or icons depending if its a volunteering event or not. it works both on show and on index. 
we are getting there!!!!!
=> map hearts

app/assets/stylesheets/components/_users_show.scss, app/controllers/users_controller.rb, app/views/users/_smallcarousel.html.erb, app/views/users/show.html.erb
friends i follow have a red  solid radius. its shit but im happy with my first css attempt!! hahaha
=)
=> friends i follow have a red radius border

app/assets/stylesheets/components/_users_show.scss, app/views/users/_eventcarrousel.html.erb, app/views/users/show.html.erb
the events the user in the profile has created has its own css class="creator". the if statement works. just need to add some scss to make it pretty!! =)
=> css selector for events the  user has created

app/controllers/users_controller.rb, app/javascript/packs/application.js, app/models/comment.rb, app/models/comment_alert.rb, app/models/event.rb, app/models/user.rb, app/views/shared/_alert.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20200304125947_create_table_comment_alerts.rb, db/migrate/20200304130237_add_read_to_comment_alerts.rb, db/schema.rb, db/seeds.rb, test/models/comment_alert_test.rb, test/models/commentalert_test.rb
the alert button  on a message. looks ugly!! it doesnt work without refreshing yet
=> alert messages works

app/views/users/show.html.erb
profiles only show event this week or this month if there are events
=> event list in profile doesnt show if its empty

app/controllers/comments_controller.rb
the messages refresh automatically now!! =)
=> messages are there without refresh

app/views/users/show.html.erb, db/migrate/20200305102201_add_about_to_users.rb, db/schema.rb
about user migration. change in user view
=> about user migration
